name: Build and Test Docker Image

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    # Name of this repository
    IMAGE_NAME: dind-demo
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
        -   name: Checkout code
            uses: actions/checkout@v3

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

        -   name: Extract commit hash
            id: extract
            run: |
                echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

        -   name: Convert repository owner to lowercase
            id: lowercase_owner
            run: |
                owner_lowercase=$(echo '${{ toJSON(github.repository_owner) }}' | tr '[:upper:]' '[:lower:]')
                # Remove double quotes from the output
                owner_lowercase=${owner_lowercase//\"}
                echo "owner_lowercase=$owner_lowercase" >> $GITHUB_OUTPUT

        -   name: Login to GitHub Container Registry
            uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

        -   name: Build and push image with commit hash tag
            uses: docker/build-push-action@v4
            with:
                context: .
                push: true
                tags: ghcr.io/${{ steps.lowercase_owner.outputs.owner_lowercase }}/${{ env.IMAGE_NAME }}:${{ steps.extract.outputs.commit_hash }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

        -   name: Test the image
            run: |
                docker run --rm ghcr.io/${{ steps.lowercase_owner.outputs.owner_lowercase }}/${{ env.IMAGE_NAME }}:${{ steps.extract.outputs.commit_hash }} curl --version

        -   name: Push image with ref slug tag
            uses: docker/build-push-action@v4
            with:
                context: .
                push: true
                tags: ghcr.io/${{ steps.lowercase_owner.outputs.owner_lowercase }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
