name: Cleanup Docker Image Tags

env:
  IMAGE_NAME: dind-demo

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use common steps
        id: common
        uses: ./.github/actions/common

      - name: Cleanup old image tags
        uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script-path: .github/scripts/cleanup_artifacts.js
