name: Common Steps

on: 
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  main: 
    runs-on: ubuntu-latest
    outputs:
      owner_lowercase: ${{ steps.lowercase_owner.outputs.owner_lowercase }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert repository owner to lowercase
        id: lowercase_owner
        run: |
          owner_lowercase=$(echo '${{ toJSON(github.repository_owner) }}' | tr '[:upper:]' '[:lower:]')
          # Remove double quotes from the output
          owner_lowercase=${owner_lowercase//\"}
          echo "owner_lowercase=$owner_lowercase" >> $GITHUB_OUTPUT
